#!/bin/sh
export PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin

AUTH=/tmp/auth.json
[ -f "$AUTH" ] || echo "{}" > "$AUTH"

docker run --user $(id -u):$(id -g) --rm --interactive --tty -v /tmp:/tmp -v $(pwd):/app composer:latest "$@"
