#!/bin/sh
export PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin

AUTH=/tmp/auth.json
[ -f "$AUTH" ] || echo "{}" > "$AUTH"

docker run --rm --interactive --tty -v $AUTH:$AUTH -v $(pwd):/app composer:latest "$@"
